apiVersion: v1
kind: Pod
metadata:
  name: nginxwebserver
spec:
  containers:
  -  image: nginx
     name: democontainer


kubectl apply -f newpod.yaml

#### List the Running Pods
kubectl get pods
#### Delete the Resources Created via newpod.yaml file
kubectl delete -f newpod.yaml
